# Generated by Django 5.1.5 on 2025-02-10 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('shipped', 'Đã giao hàng'), ('delivered', 'Đã nhận hàng'), ('canceled', 'Đã hủy')], default='pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('action', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
