# Generated by Django 5.1.5 on 2025-02-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
    ]
