# Generated by Django 5.1.5 on 2025-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Notification', '0003_notification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/'),
        ),
    ]
