# Generated by Django 5.1.5 on 2025-02-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Notification', '0006_alter_notification_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='meida/product_images/'),
        ),
    ]
