# Generated by Django 5.1.5 on 2025-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Notification', '0008_alter_notification_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
