# Generated by Django 5.1.4 on 2025-01-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('Userid', models.IntegerField(unique=True)),
                ('UserPhone', models.CharField(max_length=15, unique=True)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.paymentmethod')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Payment.user')),
            ],
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='Payment.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('IsRead', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Payment.user')),
            ],
        ),
    ]
