# Generated by Django 5.0.10 on 2024-12-26 03:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('USERID', models.AutoField(primary_key=True, serialize=False)),
                ('USERNAME', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=50, unique=True)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('UserPhone', models.CharField(blank=True, max_length=15, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('ROLE', models.IntegerField(blank=True, null=True)),
                ('CREATE_AT', models.DateTimeField(default=django.utils.timezone.now)),
                ('UPDATE_AT', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
