# Generated by Django 5.0.10 on 2025-01-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='USERID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='USERNAME', max_length=50)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EMAIL', max_length=50, unique=True)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PASSWORD', max_length=255)),
                ('userphone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserPhone', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ADDRESS', max_length=255, null=True)),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Guest'), (1, 'Customer'), (2, 'Sales'), (3, 'Staff'), (4, 'Delivery Staff'), (5, 'Manager'), (6, 'Admin')], db_column='ROLE', null=True)),
                ('create_at', models.DateTimeField(blank=True, db_column='CREATE_AT', null=True)),
                ('update_at', models.DateTimeField(blank=True, db_column='UPDATE_AT', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
