# Generated by Django 5.1.4 on 2024-12-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifi_Service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
