# Generated by Django 5.1.4 on 2024-12-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifi_Service', '0002_rename_sent_at_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Thông báo', 'verbose_name_plural': 'Các thông báo'},
        ),
        migrations.AddField(
            model_name='notification',
            name='product_image',
            field=models.URLField(blank=True, null=True, verbose_name='Ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Email khách hàng'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
