# Generated by Django 5.1.4 on 2024-12-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifi_Service', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('delivered', 'Đã Giao'), ('processing', 'Đang Xử Lí'), ('cancelled', 'Đã Huỷ'), ('shipping', 'Đang Vận Chuyển'), ('info', 'Thông tin')], max_length=20, verbose_name='Trạng Thái'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Mã Đơn Hàng'),
        ),
    ]
