# Generated by Django 5.1.4 on 2024-12-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifi_Service', '0004_alter_notification_message_alter_notification_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='product_image',
        ),
        migrations.AddField(
            model_name='notification',
            name='product_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link ảnh sản phẩm'),
        ),
    ]
