# Generated by Django 5.1.4 on 2024-12-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifi_Service', '0005_remove_notification_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('Delivered', 'Đã Giao'), ('Processing', 'Đang Xử Lí'), ('Cancelled', 'Đã Huỷ'), ('Shipping', 'Đang Vận Chuyển'), ('Info', 'Thông tin')], max_length=20, verbose_name='Trạng Thái'),
        ),
    ]
