# Generated by Django 4.2.17 on 2025-02-18 15:42

from django.db import migrations, models
import quanly.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(default=quanly.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('Pname', models.CharField(max_length=255)),
                ('descPr', models.TextField()),
                ('carat_weight', models.FloatField()),
                ('origin', models.CharField(max_length=255)),
                ('clarity', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('kim_cuong', 'Kim Cương'), ('vang', 'Vàng'), ('bac', 'Bạc'), ('day_chuyen', 'Dây chuyền'), ('nhan', 'Nhẫn'), ('vong', 'Vòng'), ('bong_tai', 'Bông tai'), ('lac_tay', 'Lắc tay'), ('dong_ho', 'Đồng hồ'), ('trang_suc_cuoi', 'Trang sức cưới')], max_length=255)),
                ('cut', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('color', models.CharField(max_length=255)),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_count', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
            ],
        ),
    ]
