# Generated by Django 4.2.17 on 2025-02-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
