# Generated by Django 5.1.5 on 2025-02-11 19:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import pj_home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('size_ni', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('descID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('category_desc', models.CharField(max_length=255)),
                ('name_desc', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='descriptions/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('Pname', models.CharField(max_length=255)),
                ('descPr', models.TextField()),
                ('carat_weight', models.FloatField()),
                ('origin', models.CharField(max_length=255)),
                ('clarity', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('cut', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('color', models.CharField(max_length=255)),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('is_read', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.order')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('pointID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('exchange_point', models.IntegerField()),
                ('point_used', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pj_home.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pj_home.user'),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('warrantyID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('claim', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistID', models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.product')),
            ],
        ),
    ]
