# Generated by Django 5.1.5 on 2025-02-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
