# Generated by Django 5.1.5 on 2025-02-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0002_product_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
