# Generated by Django 5.1.5 on 2025-02-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0003_product_sold_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='stock',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('canceled', 'Đã hủy')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
