# Generated by Django 5.1.5 on 2025-02-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kim_cuong', 'Kim Cương'), ('vang', 'Vàng'), ('bac', 'Bạc'), ('day_chuyen', 'Dây chuyền'), ('nhan', 'Nhẫn'), ('vong', 'Vòng'), ('bong_tai', 'Bông tai'), ('lac_tay', 'Lắc tay'), ('dong_ho', 'Đồng hồ'), ('trang_suc_cuoi', 'Trang sức cưới')], max_length=255),
        ),
    ]
