# Generated by Django 5.1.5 on 2025-02-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
