# Generated by Django 4.2.17 on 2025-02-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0008_remove_cart_amount_alter_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='stock',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pj_home.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
