# Generated by Django 4.2.17 on 2025-02-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0009_remove_cartitem_stock_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Guest'), (2, 'Customer'), (3, 'SaleStaff'), (4, 'Delivery Staff'), (5, 'Manager'), (6, 'Admin')], max_length=10),
        ),
    ]
