# Generated by Django 4.2.17 on 2025-02-18 15:23

from django.db import migrations, models
import pj_home.models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0010_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='terms',
        ),
        migrations.AddField(
            model_name='warranty',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('active', 'Còn hiệu lực'), ('expired', 'Hết hạn'), ('claimed', 'Đã yêu cầu'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='warrantyID',
            field=models.CharField(default=pj_home.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
