# Generated by Django 4.2.17 on 2025-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0014_viewedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.BooleanField(default=True),
        ),
    ]
