# Generated by Django 4.2.17 on 2025-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0015_order_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Guest'), (2, 'Customer'), (3, 'SaleStaff'), (4, 'Delivery Staff'), (5, 'Manager'), (6, 'Admin')]),
        ),
    ]
