# Generated by Django 4.2.17 on 2025-02-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pj_home', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.user'),
        ),
        migrations.AlterField(
            model_name='viewedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pj_home.user'),
        ),
    ]
