# Generated by Django 5.1.4 on 2024-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.AddField(
            model_name='diamond',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diamonds/'),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='carat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='clarity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
