# Generated by Django 5.0.10 on 2025-01-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0003_delete_product_remove_transaction_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diamond',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
