# Generated by Django 5.0.10 on 2025-01-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0004_diamond_description_alter_diamond_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
