# Generated by Django 5.0.10 on 2025-01-06 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0005_alter_diamond_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='diamond',
            name='carat',
        ),
        migrations.RemoveField(
            model_name='diamond',
            name='clarity',
        ),
        migrations.RemoveField(
            model_name='diamond',
            name='color',
        ),
        migrations.RemoveField(
            model_name='diamond',
            name='cut',
        ),
        migrations.AddField(
            model_name='diamond',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diamond',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='diamond',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
