# Generated by Django 5.0.10 on 2025-01-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0009_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Còn hàng', 'Còn hàng'), ('Hết hàng', 'Hết hàng')], default='Còn hàng', max_length=50),
        ),
    ]
