# Generated by Django 5.1.4 on 2025-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaName', models.CharField(max_length=100)),
                ('carat', models.FloatField()),
                ('shape', models.CharField(choices=[('Round', 'Round'), ('Princess', 'Princess'), ('Oval', 'Oval'), ('Emerald', 'Emerald'), ('Cushion', 'Cushion'), ('Marquise', 'Marquise'), ('Pear', 'Pear'), ('Asscher', 'Asscher'), ('Radiant', 'Radiant'), ('Heart', 'Heart')], max_length=20)),
                ('cut', models.CharField(choices=[('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('clarity', models.CharField(max_length=100)),
                ('DiamondPrice', models.FloatField()),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
