# Generated by Django 5.1.4 on 2025-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diamond_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond',
            name='cut',
            field=models.CharField(choices=[('Bad', 'Bad'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], max_length=100),
        ),
    ]
