# Generated by Django 5.1.4 on 2025-01-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diamond_management_app', '0002_alter_diamond_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diamonds/'),
        ),
    ]
