# Generated by Django 4.2.17 on 2025-02-13 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quanly.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(default=quanly.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('size_ni', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.CharField(default=quanly.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='quanly.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(default=quanly.models.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('carat_weight', models.FloatField()),
                ('origin', models.CharField(max_length=255)),
                ('clarity', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('cut', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('sold_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('warrantyID', models.CharField(default=quanly.models.generate_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Còn hiệu lực'), ('expired', 'Hết hạn'), ('claimed', 'Đã yêu cầu'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quanly.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.product')),
            ],
        ),
    ]
